### PR TITLE
This is a test

### PR DESCRIPTION
**Pull request by dertz**

### CODE REVIEW

**Comment by jinishahpatel** [comment]
did it not work?

On Sun, Apr 15, 2012 at 4:10 PM, Douglas J. Ertz <
reply@reply.github.com

> wrote:
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/dougertz/Application master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/ncwitmobileapp/Application/pull/6
> 
> -- Commit Summary --
> - Changes after compiling
> - Uopdating readme file
> 
> -- File Changes --
> 
> M NCWITMOBILEAPP-Android/assets/README (1)
> A NCWITMOBILEAPP-Android/bin/NCWITMOBILEAPP-Android.apk (0)
> A NCWITMOBILEAPP-Android/bin/classes.dex (0)
> A NCWITMOBILEAPP-Android/bin/classes/com/ncwitmobileapp/BuildConfig.class
> (0)
> M NCWITMOBILEAPP-Android/bin/classes/com/ncwitmobileapp/R$string.class (0)
> A NCWITMOBILEAPP-Android/bin/jarlist.cache (3)
> A NCWITMOBILEAPP-Android/bin/res/drawable-hdpi/app_icon.png (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-hdpi/gradient.png (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-hdpi/ic_mailboxes_accounts.png
> (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-hdpi/status_icon.png (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-mdpi/app_icon.png (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-mdpi/gradient.png (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-mdpi/ic_mailboxes_accounts.png
> (0)
> A NCWITMOBILEAPP-Android/bin/res/drawable-mdpi/status_icon.png (0)
> A NCWITMOBILEAPP-Android/bin/resources.ap_ (0)
> A NCWITMOBILEAPP-Android/gen/com/ncwitmobileapp/BuildConfig.java (6)
> M NCWITMOBILEAPP-Android/gen/com/ncwitmobileapp/Manifest.java (32)
> M NCWITMOBILEAPP-Android/gen/com/ncwitmobileapp/R.java (234)
> M NCWITMOBILEAPP-Android/res/values/strings.xml (12)
> D
> NCWITMOBILEAPP-AppEngine/.apt_generated/com/ncwitmobileapp/client/MyRequestFactoryDeobfuscatorBuilder.java
> (43)
> M NCWITMOBILEAPP-AppEngine/.gwt/.gwt-log (24313)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-0000013651945582 (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-00000136529BDDAE (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-00000136529D1DFE (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-00000136529E69F6 (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-00000136529FC7E0 (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-0000013652A2AB9F (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-0000013652B4D170 (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-0000013656F216E2 (0)
> A NCWITMOBILEAPP-AppEngine/gwt-unitCache/gwt-unitCache-0000013656F4CBE0 (0)
> A
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/appengine-generated/datastore-indexes-auto.xml
> (4)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/MyRequestFactory$HelloWorldRequest.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/MyRequestFactory$MessageRequest.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/MyRequestFactory$RegistrationInfoRequest.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/MyRequestFactory.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/MyRequestFactoryDeobfuscatorBuilder.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPP.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$1.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$2$1.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$2.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$3$1.class
> (0)
> D
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$3.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget$NCWITMOBILEAPPUiBinder.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/client/NCWITMOBILEAPPWidget.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/DeviceInfo.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/HelloWorldService.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/Message.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/MessageLocator.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/RegistrationInfo.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/server/SendMessage.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/shared/MessageProxy.class
> (0)
> M
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/classes/com/ncwitmobileapp/shared/RegistrationInfoProxy.class
> (0)
> A
> NCWITMOBILEAPP-AppEngine/war/WEB-INF/deploy/ncwitmobileapp/rpcPolicyManifest/manifest.txt
> (2)
> A NCWITMOBILEAPP-AppEngine/war/ncwitmobileapp/clear.cache.gif (0)
> A NCWITMOBILEAPP-AppEngine/war/ncwitmobileapp/hosted.html (364)
> A NCWITMOBILEAPP-AppEngine/war/ncwitmobileapp/ncwitmobileapp.nocache.js
> (16)
> 
> -- Patch Links --
> 
>  https://github.com/ncwitmobileapp/Application/pull/6.patch
>  https://github.com/ncwitmobileapp/Application/pull/6.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ncwitmobileapp/Application/pull/6

## 

Thank you for your time

Jinisha Patel
(973) 960-8292

**Comment by ncwitmobileapp** [comment]
this was a test

**Comment by jinishahpatel** [comment]
Okay, but you received the files right?

On Sun, Apr 15, 2012 at 4:17 PM, NCWIT Mobile Application <
reply@reply.github.com

> wrote:
> 
> this was a test
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142249

## 

Thank you for your time

Jinisha Patel
(973) 960-8292

**Comment by dertz** [comment]
Yes it did not work.  I am trying to figure out what you did.
It looks like you closed the pull request.  You do not want.  If you clode
it, that mean the changes will not get pulled into the master.

 Douglas J. Ertz
Email: dougertz@gmail.com dertz@comcast.net
Phone (home): 303-444-9136
Cell:  720-466-0083
Fax:  303-444-3505

If you think shy, you act shy. If you think confident you act confident.
Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
[image: Tungle.me] http://www.tungle.me/douglasertz [image:
Twitter]https://twitter.com/#!/dougertz [image:
LinkedIn] http://www.linkedin.com/in/douglasertz
 Want a signature like mine?
http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
Click
here.http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16

On Sun, Apr 15, 2012 at 2:13 PM, jinishahpatel <
reply@reply.github.com

**Comment by dertz** [comment]
no

Douglas J. Ertz
Email: dougertz@gmail.com dertz@comcast.net
Phone (home): 303-444-9136
Cell:  720-466-0083
Fax:  303-444-3505

If you think shy, you act shy. If you think confident you act confident.
Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
[image: Tungle.me] http://www.tungle.me/douglasertz [image:
Twitter]https://twitter.com/#!/dougertz [image:
LinkedIn] http://www.linkedin.com/in/douglasertz
 Want a signature like mine?
http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
Click
here.http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16

On Sun, Apr 15, 2012 at 2:22 PM, jinishahpatel <
reply@reply.github.com

**Comment by jinishahpatel** [comment]
it says :
Oops! The ncwitmobileapp:master branch is already up-to-date with
jinishahpatel:LoginScreen — maybe you want to try something else?

On Sun, Apr 15, 2012 at 4:27 PM, Douglas J. Ertz <
reply@reply.github.com

> wrote:
> 
> no
> 
> Douglas J. Ertz
> Email: dougertz@gmail.com dertz@comcast.net
> Phone (home): 303-444-9136
> Cell:  720-466-0083
> Fax:  303-444-3505
> 
> If you think shy, you act shy. If you think confident you act confident.
> Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
> [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> Twitter]https://twitter.com/#!/dougertz [image:
> LinkedIn] http://www.linkedin.com/in/douglasertz
>  Want a signature like mine?
> <
> http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> > Click
> > here.<
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> On Sun, Apr 15, 2012 at 2:22 PM, jinishahpatel <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Okay, but you received the files right?
> > 
> > On Sun, Apr 15, 2012 at 4:17 PM, NCWIT Mobile Application <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > this was a test
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142249
> > 
> > 
> > ## 
> > 
> > Thank you for your time
> > 
> > Jinisha Patel
> > (973) 960-8292
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142295
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142345

## 

Thank you for your time

Jinisha Patel
(973) 960-8292

**Comment by dertz** [comment]
I never pulled in those changes.     How did they get in?
You removed 3 files?

Douglas J. Ertz
Email: dougertz@gmail.com dertz@comcast.net
Phone (home): 303-444-9136
Cell:  720-466-0083
Fax:  303-444-3505

If you think shy, you act shy. If you think confident you act confident.
Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
[image: Tungle.me] http://www.tungle.me/douglasertz [image:
Twitter]https://twitter.com/#!/dougertz [image:
LinkedIn] http://www.linkedin.com/in/douglasertz
 Want a signature like mine?
http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
Click
here.http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16

On Sun, Apr 15, 2012 at 2:29 PM, jinishahpatel <
reply@reply.github.com

**Comment by jinishahpatel** [comment]
i didn't remove any files... they were just the ones i created.

On Sun, Apr 15, 2012 at 6:04 PM, Douglas J. Ertz <
reply@reply.github.com

> wrote:
> 
> I never pulled in those changes.     How did they get in?
> You removed 3 files?
> 
> Douglas J. Ertz
> Email: dougertz@gmail.com dertz@comcast.net
> Phone (home): 303-444-9136
> Cell:  720-466-0083
> Fax:  303-444-3505
> 
> If you think shy, you act shy. If you think confident you act confident.
> Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
> [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> Twitter]https://twitter.com/#!/dougertz [image:
> LinkedIn] http://www.linkedin.com/in/douglasertz
>  Want a signature like mine?
> <
> http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> > Click
> > here.<
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> On Sun, Apr 15, 2012 at 2:29 PM, jinishahpatel <
> reply@reply.github.com
> 
> > wrote:
> > 
> > it says :
> > Oops! The ncwitmobileapp:master branch is already up-to-date with
> > jinishahpatel:LoginScreen — maybe you want to try something else?
> > 
> > On Sun, Apr 15, 2012 at 4:27 PM, Douglas J. Ertz <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > no
> > > 
> > > Douglas J. Ertz
> > > Email: dougertz@gmail.com dertz@comcast.net
> > > Phone (home): 303-444-9136
> > > Cell:  720-466-0083
> > > Fax:  303-444-3505
> > > 
> > > If you think shy, you act shy. If you think confident you act
> > > confident.
> > > Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
> > > [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> > > Twitter]https://twitter.com/#!/dougertz [image:
> > > LinkedIn] http://www.linkedin.com/in/douglasertz
> > >  Want a signature like mine?
> > > <
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > > Click
> > > > here.<
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > On Sun, Apr 15, 2012 at 2:22 PM, jinishahpatel <
> > > reply@reply.github.com
> > > 
> > > > wrote:
> > > > 
> > > > Okay, but you received the files right?
> > > > 
> > > > On Sun, Apr 15, 2012 at 4:17 PM, NCWIT Mobile Application <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > this was a test
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142249
> > 
> > > > ## 
> > > > 
> > > > Thank you for your time
> > > > 
> > > > Jinisha Patel
> > > > (973) 960-8292
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142295
> > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142345
> > 
> > 
> > ## 
> > 
> > Thank you for your time
> > 
> > Jinisha Patel
> > (973) 960-8292
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142357
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5143019

## 

Thank you for your time

Jinisha Patel
(973) 960-8292

**Comment by dertz** [comment]
The shared directory is gone in App Engine
It was there previously

Douglas J. Ertz
Email: dougertz@gmail.com dertz@comcast.net
Phone (home): 303-444-9136
Cell:  720-466-0083
Fax:  303-444-3505

If you think shy, you act shy. If you think confident you act confident.
Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
[image: Tungle.me] http://www.tungle.me/douglasertz [image:
Twitter]https://twitter.com/#!/dougertz [image:
LinkedIn] http://www.linkedin.com/in/douglasertz
 Want a signature like mine?
http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
Click
here.http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16

On Sun, Apr 15, 2012 at 4:04 PM, jinishahpatel <
reply@reply.github.com

**Comment by jinishahpatel** [comment]
I have it.. i wouldn't know why it would be gone.

On Sun, Apr 15, 2012 at 6:09 PM, Douglas J. Ertz <
reply@reply.github.com

> wrote:
> 
> The shared directory is gone in App Engine
> It was there previously
> 
> Douglas J. Ertz
> Email: dougertz@gmail.com dertz@comcast.net
> Phone (home): 303-444-9136
> Cell:  720-466-0083
> Fax:  303-444-3505
> 
> If you think shy, you act shy. If you think confident you act confident.
> Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
> [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> Twitter]https://twitter.com/#!/dougertz [image:
> LinkedIn] http://www.linkedin.com/in/douglasertz
>  Want a signature like mine?
> <
> http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> > Click
> > here.<
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> 
> On Sun, Apr 15, 2012 at 4:04 PM, jinishahpatel <
> reply@reply.github.com
> 
> > wrote:
> > 
> > i didn't remove any files... they were just the ones i created.
> > 
> > On Sun, Apr 15, 2012 at 6:04 PM, Douglas J. Ertz <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > I never pulled in those changes.     How did they get in?
> > > You removed 3 files?
> > > 
> > > Douglas J. Ertz
> > > Email: dougertz@gmail.com dertz@comcast.net
> > > Phone (home): 303-444-9136
> > > Cell:  720-466-0083
> > > Fax:  303-444-3505
> > > 
> > > If you think shy, you act shy. If you think confident you act
> > > confident.
> > > Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
> > > [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> > > Twitter]https://twitter.com/#!/dougertz [image:
> > > LinkedIn] http://www.linkedin.com/in/douglasertz
> > >  Want a signature like mine?
> > > <
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > > Click
> > > > here.<
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > On Sun, Apr 15, 2012 at 2:29 PM, jinishahpatel <
> > > reply@reply.github.com
> > > 
> > > > wrote:
> > > > 
> > > > it says :
> > > > Oops! The ncwitmobileapp:master branch is already up-to-date with
> > > > jinishahpatel:LoginScreen — maybe you want to try something else?
> > > > 
> > > > On Sun, Apr 15, 2012 at 4:27 PM, Douglas J. Ertz <
> > > > reply@reply.github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > no
> > > > > 
> > > > > Douglas J. Ertz
> > > > > Email: dougertz@gmail.com dertz@comcast.net
> > > > > Phone (home): 303-444-9136
> > > > > Cell:  720-466-0083
> > > > > Fax:  303-444-3505
> > > > > 
> > > > > If you think shy, you act shy. If you think confident you act
> > > > > confident.
> > > > > Therefore never let shyness conquer your mind. -  _Arfa Karim
> > > > > Randhawa_
> > > > > [image: Tungle.me] http://www.tungle.me/douglasertz [image:
> > > > > Twitter]https://twitter.com/#!/dougertz [image:
> > > > > LinkedIn] http://www.linkedin.com/in/douglasertz
> > > > >  Want a signature like mine?
> > > > > <
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > > > > Click
> > > > > > here.<
> > 
> > http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
> > 
> > > > > On Sun, Apr 15, 2012 at 2:22 PM, jinishahpatel <
> > > > > reply@reply.github.com
> > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > Okay, but you received the files right?
> > > > > > 
> > > > > > On Sun, Apr 15, 2012 at 4:17 PM, NCWIT Mobile Application <
> > > > > > reply@reply.github.com
> > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > this was a test
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142249
> > 
> > > > > > ## 
> > > > > > 
> > > > > > Thank you for your time
> > > > > > 
> > > > > > Jinisha Patel
> > > > > > (973) 960-8292
> > > > > > 
> > > > > > ---
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142295
> > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142345
> > 
> > > > ## 
> > > > 
> > > > Thank you for your time
> > > > 
> > > > Jinisha Patel
> > > > (973) 960-8292
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5142357
> > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5143019
> > 
> > 
> > ## 
> > 
> > Thank you for your time
> > 
> > Jinisha Patel
> > (973) 960-8292
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5143024
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ncwitmobileapp/Application/pull/6#issuecomment-5143053

## 

Thank you for your time

Jinisha Patel
(973) 960-8292

**Comment by dertz** [comment]
Please send a pull request so I can get it into the repository

Douglas J. Ertz
Email: dougertz@gmail.com dertz@comcast.net
Phone (home): 303-444-9136
Cell:  720-466-0083
Fax:  303-444-3505

If you think shy, you act shy. If you think confident you act confident.
Therefore never let shyness conquer your mind. -  _Arfa Karim Randhawa_
[image: Tungle.me] http://www.tungle.me/douglasertz [image:
Twitter]https://twitter.com/#!/dougertz [image:
LinkedIn] http://www.linkedin.com/in/douglasertz
 Want a signature like mine?
http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16
Click
here.http://r1.wisestamp.com/r/landing?promo=16&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_16

On Sun, Apr 15, 2012 at 4:19 PM, jinishahpatel <
reply@reply.github.com

**Pull request closed without merging**
